name: "Pull Request/Issues Triage"
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  issues:
    types: [opened, reopened, edited]

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
    - name: Pull Request Labeler
      if: github.event.pull_request
      uses: actions/labeler@v4
    
    - name: Issue Labeler
      if: github.event.issue
      uses: github/issue-labeler@v3.2
      with:
        enable-versioned-regex: 0
        configuration-path: .github/issue-labeler.yml
  remove-unnecesary-files:
    runs-on: ubuntu-latest
    steps:
    - name: Remove Unnecessary Files
      uses: dorny/paths-filter@v2
      id: files_changed
      with:
        filters: |
          langs: 
            - '!chameleonultragui/lib/l10n/*en.arb'
            - 'chameleonultragui/lib/l10n/*.arb'
