name: "Pull Request/Issues Triage"
on:
  pull_request:

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Pull Request Labeler
      if: github.event.pull_request
      uses: actions/labeler@v4
  remove-unnecesary-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v3
    - name: Detect changed languages files
      uses: dorny/paths-filter@v2
      id: files_changed
      with:
        filters: |
          langs: 
            - '!chameleonultragui/lib/l10n/*en.arb'
            - 'chameleonultragui/lib/l10n/*.arb'
    - name: Remove unnecesary files
      id: removed
      if: steps.files_changed.outputs.langs == 'true'
      working-directory: chameleonultragui/lib/l10n
      run: |
        git fetch origin
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        for file in $(ls *.arb); do
          if [[ "$file" != "app_en.arb" ]]; then
            git checkout origin/main -- $file
          fi
        done
    - name: Create commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Uncommitted translation files
        commit_options: '--no-verify'
        status_options: '--untracked-files=no'
        add_options: '-u'
        push_options: '--force'
        skip_dirty_check: false
        skip_fetch: true
        skip_checkout: true
        disable_globbing: true