name: "Pull Request Triage"
on:
- pull_request_target

jobs:
  labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
  remove-unnecesary-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed .arb files
        run: |
          arb_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.arb$' | grep -v 'app_en.arb')
          echo "$arb_files" > arb_files.txt